-- Generated by scripts/sync-may-2026.py
-- Mirrors the 'All Filter Sell Price' Excel tab into parts.* override columns
-- (parts.without_service_price, parts.with_service_price, parts.over_counter_price).
-- Apply AFTER migration 0055_parts_sell_price_overrides.sql.
--
-- Only updates existing parts (matched by part_number). New parts must be created
-- via the Pricing catalogue admin or a separate seed (see may2026_REPORT.md).

begin;

update public.parts set without_service_price = 409.99, with_service_price    = 399.99, over_counter_price    = 399.99
  where part_number = '03-36867-010';

update public.parts set without_service_price = 179.99, with_service_price    = 169.99, over_counter_price    = 169.99
  where part_number = '03-42776-010';

update public.parts set without_service_price = 230.99, with_service_price    = 220.99, over_counter_price    = 220.99
  where part_number = '03-43216-010';

update public.parts set without_service_price = 144.99, with_service_price    = 144.99, over_counter_price    = 144.99
  where part_number = '21715813';

update public.parts set without_service_price = 359.99, with_service_price    = 359.99, over_counter_price    = 359.99
  where part_number = '23883251';

update public.parts set without_service_price = 231.99, with_service_price    = 231.99, over_counter_price    = 231.99
  where part_number = '2515573C1';

update public.parts set without_service_price = 661.99, with_service_price    = 661.99, over_counter_price    = 661.99
  where part_number = '2599273C92';

update public.parts set without_service_price = 135.99, with_service_price    = 125.99, over_counter_price    = 115.99
  where part_number = '4329012482';

update public.parts set without_service_price = 49.99, with_service_price    = 49.99, over_counter_price    = 49.99
  where part_number = '950011-G3';

update public.parts set without_service_price = 105.99, with_service_price    = 95.99, over_counter_price    = 85.99
  where part_number = 'AC1001';

update public.parts set without_service_price = 85.99, with_service_price    = 75.99, over_counter_price    = 60.99
  where part_number = 'AD27747';

update public.parts set without_service_price = 86.99, with_service_price    = 76.99, over_counter_price    = 61.99
  where part_number = 'AD27750';

update public.parts set without_service_price = 85.99, with_service_price    = 85.99, over_counter_price    = 85.99
  where part_number = 'AF25139M';

update public.parts set without_service_price = 79.99, with_service_price    = 79.99, over_counter_price    = 79.99
  where part_number = 'P153551';

update public.parts set without_service_price = 23.99, with_service_price    = 23.99, over_counter_price    = 23.99
  where part_number = 'AF26235';

update public.parts set without_service_price = 24.99, with_service_price    = 24.99, over_counter_price    = 24.99
  where part_number = 'AF26405';

update public.parts set without_service_price = 25.99, with_service_price    = 25.99, over_counter_price    = 25.99
  where part_number = 'AF26418';

update public.parts set without_service_price = 65.99, with_service_price    = 45.99, over_counter_price    = 52.99
  where part_number = '1752949';

update public.parts set without_service_price = 68.99, with_service_price    = null, over_counter_price    = 51.99
  where part_number = '1R0716';

update public.parts set without_service_price = 57.99, with_service_price    = null, over_counter_price    = 44.99
  where part_number = '1R0749';

update public.parts set without_service_price = 52.99, with_service_price    = null, over_counter_price    = 38.99
  where part_number = '1R0751';

update public.parts set without_service_price = 55.99, with_service_price    = null, over_counter_price    = 36.99
  where part_number = '1R1807';

update public.parts set without_service_price = 77.99, with_service_price    = 22.99, over_counter_price    = 66.99
  where part_number = '1R1808';

update public.parts set without_service_price = 63.99, with_service_price    = 43.99, over_counter_price    = 50.99
  where part_number = '2568753';

update public.parts set without_service_price = 53.99, with_service_price    = null, over_counter_price    = 34.99
  where part_number = '23530573';

update public.parts set without_service_price = 40.99, with_service_price    = null, over_counter_price    = 23.99
  where part_number = '23530706';

update public.parts set without_service_price = 40.99, with_service_price    = null, over_counter_price    = 23.99
  where part_number = '23530707';

update public.parts set without_service_price = 135.99, with_service_price    = null, over_counter_price    = 120.99
  where part_number = 'A4700903151';

update public.parts set without_service_price = 67.99, with_service_price    = null, over_counter_price    = 51.99
  where part_number = 'A4711800209';

update public.parts set without_service_price = 66.99, with_service_price    = null, over_counter_price    = 50.99
  where part_number = 'A4731800909';

update public.parts set without_service_price = 170.99, with_service_price    = null, over_counter_price    = 163.99
  where part_number = 'A9360900651';

update public.parts set without_service_price = 58.99, with_service_price    = null, over_counter_price    = 39.99
  where part_number = 'A9361807410';

update public.parts set without_service_price = 75.99, with_service_price    = null, over_counter_price    = 57.99
  where part_number = 'FF252';

update public.parts set without_service_price = 50.99, with_service_price    = null, over_counter_price    = 29.99
  where part_number = 'FF254';

update public.parts set without_service_price = 59.99, with_service_price    = null, over_counter_price    = 39.99
  where part_number = 'FF4212800-NN';

update public.parts set without_service_price = 39.99, with_service_price    = null, over_counter_price    = 16.99
  where part_number = 'FF5138';

update public.parts set without_service_price = 32.99, with_service_price    = null, over_counter_price    = 14.99
  where part_number = 'FF5206';

update public.parts set without_service_price = 33.99, with_service_price    = null, over_counter_price    = 15.99
  where part_number = 'FF5207';

update public.parts set without_service_price = 38.99, with_service_price    = null, over_counter_price    = 20.99
  where part_number = 'FF5269';

update public.parts set without_service_price = 39.99, with_service_price    = null, over_counter_price    = 22.99
  where part_number = 'FF5319';

update public.parts set without_service_price = 36.99, with_service_price    = null, over_counter_price    = 18.99
  where part_number = 'FF5321';

update public.parts set without_service_price = 48.99, with_service_price    = null, over_counter_price    = 26.99
  where part_number = 'FF5380';

update public.parts set without_service_price = 43.99, with_service_price    = null, over_counter_price    = 21.99
  where part_number = 'FF5381';

update public.parts set without_service_price = 45.99, with_service_price    = null, over_counter_price    = 23.99
  where part_number = 'FF5382';

update public.parts set without_service_price = 45.99, with_service_price    = null, over_counter_price    = 30.99
  where part_number = 'FF5405';

update public.parts set without_service_price = 46.99, with_service_price    = null, over_counter_price    = 24.99
  where part_number = 'FF5632';

update public.parts set without_service_price = 48.99, with_service_price    = 11.99, over_counter_price    = 27.99
  where part_number = 'FF5636';

update public.parts set without_service_price = 69.99, with_service_price    = null, over_counter_price    = 58.99
  where part_number = 'FF5776';

update public.parts set without_service_price = 53.99, with_service_price    = null, over_counter_price    = 34.99
  where part_number = 'FF5795';

update public.parts set without_service_price = 83.99, with_service_price    = 12.99, over_counter_price    = 67.99
  where part_number = 'FF5825-NN';

update public.parts set without_service_price = 60.99, with_service_price    = null, over_counter_price    = 36.99
  where part_number = 'FF5877';

update public.parts set without_service_price = 95.99, with_service_price    = 23.99, over_counter_price    = 83.99
  where part_number = 'FF5971-NN';

update public.parts set without_service_price = 82.99, with_service_price    = 67.99, over_counter_price    = 68.99
  where part_number = 'FF5995';

update public.parts set without_service_price = 147.99, with_service_price    = null, over_counter_price    = 138.99
  where part_number = 'FK22005';

update public.parts set without_service_price = 41.99, with_service_price    = 21.99, over_counter_price    = 23.99
  where part_number = 'FS1000';

update public.parts set without_service_price = 41.99, with_service_price    = null, over_counter_price    = 24.99
  where part_number = 'FS19624';

update public.parts set without_service_price = 45.99, with_service_price    = 30.99, over_counter_price    = 29.99
  where part_number = 'FS19764';

update public.parts set without_service_price = 46.99, with_service_price    = 31.99, over_counter_price    = 30.99
  where part_number = 'FS19765';

update public.parts set without_service_price = 51.99, with_service_price    = null, over_counter_price    = 30.99
  where part_number = 'LF16046';

update public.parts set without_service_price = 40.99, with_service_price    = null, over_counter_price    = 17.99
  where part_number = 'LF16102';

update public.parts set without_service_price = 47.99, with_service_price    = null, over_counter_price    = 25.99
  where part_number = 'LF16110';

update public.parts set without_service_price = 64.99, with_service_price    = null, over_counter_price    = 45.99
  where part_number = 'LF16233';

update public.parts set without_service_price = 50.99, with_service_price    = null, over_counter_price    = 29.99
  where part_number = 'LF17502';

update public.parts set without_service_price = 48.99, with_service_price    = null, over_counter_price    = 27.99
  where part_number = 'LF17503';

update public.parts set without_service_price = 60.99, with_service_price    = null, over_counter_price    = 41.99
  where part_number = 'LF17511';

update public.parts set without_service_price = 57.99, with_service_price    = null, over_counter_price    = 37.99
  where part_number = 'LF17515';

update public.parts set without_service_price = 35.99, with_service_price    = null, over_counter_price    = 13.99
  where part_number = 'LF17531';

update public.parts set without_service_price = 53.99, with_service_price    = null, over_counter_price    = 27.99
  where part_number = 'LF17537';

update public.parts set without_service_price = 84.99, with_service_price    = null, over_counter_price    = 69.99
  where part_number = 'LF17549';

update public.parts set without_service_price = 61.99, with_service_price    = null, over_counter_price    = 42.99
  where part_number = 'LF3000';

update public.parts set without_service_price = 36.99, with_service_price    = null, over_counter_price    = 14.99
  where part_number = 'LF3349';

update public.parts set without_service_price = 65.99, with_service_price    = null, over_counter_price    = 45.99
  where part_number = 'LF3586';

update public.parts set without_service_price = 44.99, with_service_price    = null, over_counter_price    = 22.99
  where part_number = 'LF3620';

update public.parts set without_service_price = 44.99, with_service_price    = null, over_counter_price    = 22.99
  where part_number = 'LF3630';

update public.parts set without_service_price = 54.99, with_service_price    = null, over_counter_price    = 34.99
  where part_number = 'LF3883';

update public.parts set without_service_price = 45.99, with_service_price    = null, over_counter_price    = 23.99
  where part_number = 'LF3914';

update public.parts set without_service_price = 40.99, with_service_price    = null, over_counter_price    = 18.99
  where part_number = 'LF3970';

update public.parts set without_service_price = 40.99, with_service_price    = null, over_counter_price    = 18.99
  where part_number = 'LF667';

update public.parts set without_service_price = 54.99, with_service_price    = 17.99, over_counter_price    = 43.99
  where part_number = 'LF9009';

update public.parts set without_service_price = 69.99, with_service_price    = null, over_counter_price    = 51.99
  where part_number = 'LF9025';

update public.parts set without_service_price = 111.99, with_service_price    = null, over_counter_price    = 99.99
  where part_number = '15613-E0110';

update public.parts set without_service_price = 157.99, with_service_price    = null, over_counter_price    = 145.99
  where part_number = '1884207C92';

update public.parts set without_service_price = 129.99, with_service_price    = null, over_counter_price    = 111.99
  where part_number = '1899332C91';

update public.parts set without_service_price = 91.99, with_service_price    = null, over_counter_price    = 78.99
  where part_number = '3004473C93';

update public.parts set without_service_price = 137.99, with_service_price    = null, over_counter_price    = 123.99
  where part_number = '3007498C94';

update public.parts set without_service_price = 80.99, with_service_price    = null, over_counter_price    = 54.99
  where part_number = '2-90654-404-0';

update public.parts set without_service_price = 63.99, with_service_price    = null, over_counter_price    = 41.99
  where part_number = '2-94561-104-0';

update public.parts set without_service_price = 77.99, with_service_price    = null, over_counter_price    = 60.99
  where part_number = '21707135';

update public.parts set without_service_price = 69.99, with_service_price    = null, over_counter_price    = 42.99
  where part_number = '21939298';

update public.parts set without_service_price = 65.99, with_service_price    = null, over_counter_price    = 40.99
  where part_number = '23658111';

update public.parts set without_service_price = 67.99, with_service_price    = null, over_counter_price    = 46.99
  where part_number = '25502421';

update public.parts set without_service_price = 84.99, with_service_price    = null, over_counter_price    = 63.99
  where part_number = '25502422';

update public.parts set without_service_price = 48.99, with_service_price    = null, over_counter_price    = 28.99
  where part_number = 'A9061800209';

update public.parts set without_service_price = 65.99, with_service_price    = null, over_counter_price    = 48.99
  where part_number = 'ME306306';

update public.parts set without_service_price = 72.99, with_service_price    = null, over_counter_price    = 49.99
  where part_number = 'QY009004';

update public.parts set without_service_price = 32.99, with_service_price    = 32.99, over_counter_price    = 32.99
  where part_number = '257000-464';

update public.parts set without_service_price = 104.99, with_service_price    = null, over_counter_price    = 85.99
  where part_number = '1948921PE';

update public.parts set without_service_price = 117.99, with_service_price    = null, over_counter_price    = 108.99
  where part_number = '2277129PE';

update public.parts set without_service_price = 70.99, with_service_price    = null, over_counter_price    = 58.99
  where part_number = '21707132';

update public.parts set without_service_price = 67.99, with_service_price    = null, over_counter_price    = 50.99
  where part_number = '22480372';

update public.parts set without_service_price = 64.99, with_service_price    = null, over_counter_price    = 39.99
  where part_number = '23658092';

update public.parts set without_service_price = 97.99, with_service_price    = null, over_counter_price    = 78.99
  where part_number = '23920469';

commit;

-- Matched 102 parts. 661 Excel rows had no matching part_number in DB (see report).
