-- Generated by scripts/sync-may-2026.py
-- Adds engine_types entries missing from the platform but present in the May 2026 Excel.
-- Existing engines are left untouched. display_name is a GENERATED column so we
-- only insert manufacturer + model.

begin;

commit;
