#!/usr/bin/env python3
"""
Generate a SQL file that seeds public.engine_sell_prices from the May 2026
Excel workbook.

USAGE:
    python3 scripts/seed-sell-prices.py
    # → writes supabase/seed/sell_prices_from_excel.sql

The output file matches engines by their `display_name`. Because the Excel
naming ("C 7 / 10 / 3126 With Cat Filter") doesn't always match what's in
engine_types.display_name ("Caterpillar C7" or similar), each INSERT is wrapped
in a `WHERE display_name = '...'` lookup — any row that doesn't match is
silently a no-op (the seed prints a comment so you can see what got skipped).

After generating, review the SQL, then apply with:
    psql ... -f supabase/seed/sell_prices_from_excel.sql
or paste into Supabase Studio's SQL editor.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required. Install with: pip3 install openpyxl")


REPO = Path(__file__).resolve().parents[1]
WORKBOOK = REPO / "doc" / "May 2026 Standard.xlsx"
OUT = REPO / "supabase" / "seed" / "sell_prices_from_excel.sql"


# Map each Excel oil-tab name to (oil_types.code, container).
TAB_MAPPING: list[tuple[str, str, str]] = [
    ("15W40",            "15W40",       "bulk"),
    ("15W40 Gallon",     "15W40",       "gallon"),
    ("10W30",            "10W30",       "bulk"),
    ("10W30 Gallon",     "10W30",       "gallon"),
    ("T5",               "T5",          "bulk"),
    ("T5 Gallon",        "T5",          "gallon"),
    ("Petro 10W30",      "PETRO_10W30", "bulk"),
    ("Petro 10W30Gallon","PETRO_10W30", "gallon"),
    ("T6",               "T6",          "bulk"),
    ("T6 Gallon",        "T6",          "gallon"),
    ("Delo 5W30",        "DELO_5W30",   "bulk"),
    ("Delo 5W30 Gallon", "DELO_5W30",   "gallon"),
    ("Petro 5W30",       "PETRO_5W30",  "bulk"),
    ("Petro 5W30 Gallon","PETRO_5W30",  "gallon"),
]


def collect_prices(wb) -> list[tuple[str, str, str, float]]:
    """Returns list of (engine_label, oil_code, container, sell_price)."""
    rows: list[tuple[str, str, str, float]] = []
    for tab, oil_code, container in TAB_MAPPING:
        if tab not in wb.sheetnames:
            print(f"  ! tab not found: {tab}", file=sys.stderr)
            continue
        sh = wb[tab]
        # Data starts at row 6 in the Excel layout (rows 1-5 are headers).
        for r in range(6, sh.max_row + 1):
            engine = sh.cell(r, 1).value  # column A
            price  = sh.cell(r, 2).value  # column B (selling price)
            if not engine or price is None:
                continue
            if not isinstance(price, (int, float)) or price <= 0:
                continue
            label = str(engine).strip()
            if not label:
                continue
            rows.append((label, oil_code, container, float(price)))
    return rows


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def build_sql(prices: list[tuple[str, str, str, float]]) -> str:
    lines: list[str] = [
        "-- Generated by scripts/seed-sell-prices.py from doc/May 2026 Standard.xlsx",
        "-- One row per (engine, oil, container). Run AFTER migration 0052.",
        "-- Each INSERT looks up engine_types by display_name and oil_types by code.",
        "-- If an engine/oil isn't found, the INSERT silently inserts 0 rows.",
        "",
        "begin;",
        "",
    ]
    for engine_label, oil_code, container, price in prices:
        lines.append(
            "insert into public.engine_sell_prices "
            "(engine_type_id, oil_type_id, container, sell_price)"
        )
        lines.append("select e.id, o.id, " + repr(container) + ", " + f"{price:.2f}")
        lines.append("  from public.engine_types e, public.oil_types o")
        lines.append(
            f"  where e.display_name = '{sql_escape(engine_label)}'"
        )
        lines.append(f"    and o.code = '{sql_escape(oil_code)}'")
        lines.append(
            "  on conflict (engine_type_id, oil_type_id, container) do update set "
            "sell_price = excluded.sell_price;"
        )
        lines.append("")
    lines.append("commit;")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not WORKBOOK.exists():
        print(f"workbook not found: {WORKBOOK}", file=sys.stderr)
        return 1

    print(f"Reading {WORKBOOK.relative_to(REPO)} …")
    wb = openpyxl.load_workbook(WORKBOOK, data_only=True, read_only=True)
    prices = collect_prices(wb)
    print(f"Collected {len(prices)} (engine, oil, container) rows")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_sql(prices))
    rel = OUT.relative_to(REPO)
    print(f"Wrote {rel}")
    print()
    print("Next steps:")
    print(f"  1) Review the generated SQL in {rel}")
    print("  2) Apply it via the Supabase SQL editor or psql:")
    print(f"     psql \"$DATABASE_URL\" -f {rel}")
    print("  3) Check the Sell-price overrides admin page — cells should now be green.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
